#  Copyright (C) 2018 Yunify, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this work except in compliance with the License.
#  You may obtain a copy of the License in the LICENSE file, or at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-qingcloud-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      role: "controller"
  template:
    metadata:
      labels:
        role: "controller"
    spec:
      serviceAccount: csi-qingcloud-controller
      containers:
      - name: csi-provisioner
        image: quay.io/k8scsi/csi-provisioner:v1.4.0-rc1
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
          requests:
            memory: "20Mi"
            cpu: "20m"
        args:
        - "--csi-address=$(ADDRESS)"
        - "--enable-leader-election"
        - "--feature-gates=Topology=true"
        - "--leader-election-type=leases"
        - "--retry-interval-max=5m"
        - "--retry-interval-start=5s"
        - "--timeout=90s"
        - "--worker-threads=5"
        - "--volume-name-prefix=pvc"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-attacher
        image: quay.io/k8scsi/csi-attacher:v2.0.0
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
          requests:
            memory: "20Mi"
            cpu: "20m"
        args:
        - "--csi-address=$(ADDRESS)"
        - "--leader-election"
        - "--retry-interval-max=5m"
        - "--retry-interval-start=5s"
        - "--timeout=90s"
        - "--worker-threads=5"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-snapshotter
        image: quay.io/k8scsi/csi-snapshotter:v1.2.1
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
          requests:
            memory: "20Mi"
            cpu: "20m"
        args:
          - "--connection-timeout=90s"
          - "--csi-address=$(ADDRESS)"
          - "--leader-election=false"
          - "--snapshot-name-prefix=snapshot"
          - "--v=5"
        env:
          - name: ADDRESS
            value: /csi/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - name: socket-dir
            mountPath: /csi
      - name: csi-resizer
        image: quay.io/k8scsi/csi-resizer:v0.2.0
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
          requests:
            memory: "20Mi"
            cpu: "20m"
        args:
          - "--csi-address=$(ADDRESS)"
          - "--leader-election"
          - "--v=5"
        env:
          - name: ADDRESS
            value: /csi/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - name: socket-dir
            mountPath: /csi
      - name: csi-qingcloud
        image: csiplugin/csi-qingcloud:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "50m"
        args :
          - "--config=/etc/config/config.yaml"
          - "--drivername=disk.csi.qingcloud.com"
          - "--endpoint=$(CSI_ENDPOINT)"
          - "--maxvolume=10"
          - "--nodeid=$(NODE_ID)"
          - "--v=5"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://csi/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: server-config
          mountPath: /etc/config
      volumes:
      - name: socket-dir
        emptyDir:
      - name: server-config
        configMap:
          name: csi-qingcloud